""" DonutCombos - Utility app to create code for multi-donuts-mod """

"""
lists
"""
icings = [ 'none', 'strawberry', 'chocolate', 'blueberry', 'vanilla' ]
sprinkles = [ 'none', 'green', 'blue', 'red', 'yellow', 'orange', 'rainbow' ]
fillings = [ 'none', 'strawberry', 'chocolate', 'vanilla', 'cookieDough', 'brownieBatter' ]
item1 = []
item2 = []
lang = []
recipe = []

"""
create item1 list
"""
for icing in icings:
    for sprinkle in sprinkles:
        for filling in fillings:
            item1.append( 'public static ItemFood ' + icing + sprinkle.capitalize() + filling.capitalize() + 'Donut;' )


"""
create item2 list
"""

"""
create lang list
"""

"""
create recipe list
"""

"""
output lists for copy/paste
"""
print ('ModItems: \n')
print ('/*\n * begin - Auto generated by DonutCombos.py\n */')
for item in item1:
    print (item)
print ('/*\n * end - Auto generated by DonutCombos.py\n */')
print ('\nloadItems: \n')
print ('/*\n * begin - Auto generated by DonutCombos.py\n */')
for item in item2:
    print (item)
print ('/*\n * end - Auto generated by DonutCombos.py\n */')
print ('\nen_US.lang: \n')
print ('/*\n * begin - Auto generated by DonutCombos.py\n */')
for item in lang:
    print (item)
print ('/*\n * end - Auto generated by DonutCombos.py\n */')
print ('\nModRecipes: \n')
print ('/*\n * begin - Auto generated by DonutCombos.py\n */')
for item in recipe:
    print (item)
print ('/*\n * end - Auto generated by DonutCombos.py\n */')
